### ISSUE TITLE
Cannot launch server from dev branch on ubuntu 22.04 WSL

### ISSUE THREAD

**Issue by tkbstudios** [acagliano/titrek-server#35]
Issue: **Cannot launch TI-TREK server from dev branch on ubuntu 22.04 64bit WSL2**

Platform: **Linux Ubuntu 22.04 64bit WSL2**
Date: 22-10-19

_Dependencies installed?_ Yes, using `pip3 install -r requirements.txt`
_Command used to launch TI-TREK server:_ `python3 runserver.py`

command output:
```
Traceback (most recent call last):
  File "runserver.py", line 2, in <module>
    from trek.server import *
  File "/home/ubuntu/titrek-server-dev/trek/server.py", line 4, in <module>
    from trek.utils.filter import *
  File "/home/ubuntu/titrek-server-dev/trek/utils/filter.py", line 39
    packet_names = list(ControlCodes.keys())
                                           ^
IndentationError: unindent does not match any outer indentation level
```

Screenshot:
![image](https://user-images.githubusercontent.com/69647028/196713753-32d1577f-2346-4afd-bf35-6bfc73de6f41.png)

**Comment by tkbstudios** [comment]
great memories, it all started here lol

**Comment by alessiodam** [comment]
This repo got me into learning more about computers. It's all your fault :P
