### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by SuperPupperDoggo** [acagliano/titrek-server#36]
It would appear the repository is missing certain data files. When I tried to set up a server following the user guide, I got the following:

`Something went wrong loading data/assets/planetoids/planets.json
Traceback (most recent call last):
  File "runserver.py", line 2, in <module>
    from trekcore.server import *
  File "/home/misc/titrek-server/trekcore/server.py", line 9, in <module>
    from trekcore.generate import *
  File "/home/misc/titrek-server/trekcore/generate.py", line 133, in <module>
    StandardPlanetList = LoadJsonFile("data/assets/planetoids/planets.json")["data"]
  File "/home/misc/titrek-server/trekcore/generate.py", line 103, in LoadJsonFile
    raise e
  File "/home/misc/titrek-server/trekcore/generate.py", line 99, in LoadJsonFile
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/assets/planetoids/planets.json'`

**Comment by tkbstudios** [comment]
@SuperPupperDoggo I am currently trying to fill up and trying to make the server work, don't forget it's still in rewrite and you need to clone the rewrite branch using `git clone -b rewrite https://github.com/acagliano/titrek-server.git`

**Comment by tkbstudios** [comment]
@SuperPupperDoggo I am closing this issue now. Just do `git clone -b rewrite https://github.com/acagliano/titrek-server.git`.

I updated a big part of the server code and it should load and you'll get an error `AttributeError: 'Server' object has no attribute 'meta'`.

I fixed about 15-20 bugs so it's already that less bugs ;)
